# Generated by Django 4.2.7 on 2025-06-09 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi marcado como deletado', null=True, verbose_name='Deletado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Nome único da configuração', max_length=100, unique=True, verbose_name='Chave')),
                ('value', models.TextField(help_text='Valor da configuração (pode ser JSON para estruturas complexas)', verbose_name='Valor')),
                ('description', models.TextField(help_text='Descrição do que essa configuração controla', verbose_name='Descrição')),
                ('data_type', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número Inteiro'), ('float', 'Número Decimal'), ('boolean', 'Verdadeiro/Falso'), ('json', 'JSON')], default='string', help_text='Tipo de dados da configuração', max_length=20, verbose_name='Tipo de Dados')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema', verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi marcado como deletado', null=True, verbose_name='Deletado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Tipo de ação realizada pelo usuário', max_length=100, verbose_name='Ação')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da ação', verbose_name='Descrição')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, help_text='Informações do navegador/dispositivo do usuário', verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atividade do Usuário',
                'verbose_name_plural': 'Atividades dos Usuários',
                'ordering': ['-created_at'],
            },
        ),
    ]
