# Generated by Django 4.2.7 on 2025-06-18 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paradas', '0001_initial'),
        ('linhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(help_text='Ordem da parada no trajeto da linha')),
                ('tempo_parada', models.PositiveIntegerField(blank=True, help_text='Tempo de parada em segundos', null=True)),
                ('distancia_origem', models.FloatField(blank=True, help_text='Distância da origem da linha em quilômetros', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre esta parada na linha')),
                ('linha', models.ForeignKey(help_text='Linha de transporte', on_delete=django.db.models.deletion.CASCADE, to='linhas.linha')),
                ('parada', models.ForeignKey(help_text='Parada de ônibus', on_delete=django.db.models.deletion.CASCADE, to='paradas.parada')),
            ],
            options={
                'verbose_name': 'Linha-Parada',
                'verbose_name_plural': 'Linhas-Paradas',
                'ordering': ['linha', 'ordem'],
                'indexes': [models.Index(fields=['linha', 'ordem'], name='linhas_linh_linha_i_a337c8_idx')],
                'unique_together': {('linha', 'ordem'), ('linha', 'parada')},
            },
        ),
    ]
