# Generated by Django 4.2.7 on 2025-06-18 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dftrans', models.CharField(help_text='Código oficial da parada no sistema DFTrans', max_length=20, unique=True)),
                ('nome', models.CharField(help_text='Nome oficial da parada', max_length=255)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da localização')),
                ('latitude', models.FloatField(help_text='Latitude da parada')),
                ('longitude', models.FloatField(help_text='Longitude da parada')),
                ('tipo', models.CharField(choices=[('main', 'Principal'), ('secondary', 'Secundária'), ('terminal', 'Terminal'), ('metro', 'Estação de Metrô'), ('airport', 'Aeroporto'), ('hospital', 'Hospital'), ('shopping', 'Shopping'), ('education', 'Educacional')], default='secondary', help_text='Tipo da parada', max_length=20)),
                ('tem_acessibilidade', models.BooleanField(default=False, help_text='Indica se a parada tem recursos de acessibilidade')),
                ('tem_cobertura', models.BooleanField(default=False, help_text='Indica se a parada tem cobertura/abrigo')),
                ('tem_banco', models.BooleanField(default=False, help_text='Indica se a parada tem bancos para sentar')),
                ('movimento_estimado', models.PositiveIntegerField(default=0, help_text='Número estimado de passageiros por dia', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('endereco', models.CharField(blank=True, help_text='Endereço completo da parada', max_length=500)),
                ('pontos_referencia', models.TextField(blank=True, help_text='Pontos de referência próximos à parada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['codigo_dftrans'], name='paradas_par_codigo__7f3187_idx'), models.Index(fields=['tipo'], name='paradas_par_tipo_c04802_idx'), models.Index(fields=['tem_acessibilidade'], name='paradas_par_tem_ace_505f3e_idx')],
            },
        ),
    ]
