# Generated by Django 4.2.7 on 2025-06-11 00:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.CharField(choices=[('weekday', 'Dias úteis'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=10, verbose_name='Tipo de dia')),
                ('start_time', models.TimeField(verbose_name='Horário inicial')),
                ('end_time', models.TimeField(verbose_name='Horário final')),
                ('frequency_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='Frequência (minutos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='routes.busroute', verbose_name='Rota')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'unique_together': {('route', 'day_type', 'start_time', 'end_time')},
            },
        ),
    ]
