# Generated by Django 4.2.7 on 2025-06-11 10:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['route__number', 'day_type', 'direction', 'start_time'], 'verbose_name': 'Horário', 'verbose_name_plural': 'Horários'},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schedule',
            name='direction',
            field=models.CharField(choices=[('ida', 'Ida'), ('volta', 'Volta'), ('circular', 'Circular')], default='ida', max_length=10, verbose_name='Direção'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações especiais sobre este horário', verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='peak_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim do horário de pico'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='peak_frequency_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Frequência reduzida nos horários de pico', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='Frequência no pico (minutos)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='peak_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Início do horário de pico'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_type',
            field=models.CharField(choices=[('weekday', 'Dias úteis'), ('saturday', 'Sábado'), ('sunday', 'Domingo'), ('holiday', 'Feriado')], max_length=10, verbose_name='Tipo de dia'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frequency_minutes',
            field=models.PositiveIntegerField(help_text='Intervalo entre partidas em minutos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='Frequência (minutos)'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('route', 'day_type', 'direction', 'start_time', 'end_time')},
        ),
        migrations.CreateModel(
            name='SpecialSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('direction', models.CharField(choices=[('ida', 'Ida'), ('volta', 'Volta'), ('circular', 'Circular')], default='ida', max_length=10, verbose_name='Direção')),
                ('description', models.CharField(help_text='Ex: Natal, Ano Novo, etc.', max_length=200, verbose_name='Descrição')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Horário inicial')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Horário final')),
                ('frequency_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='Frequência (minutos)')),
                ('is_suspended', models.BooleanField(default=False, help_text='Marca se o serviço está suspenso nesta data', verbose_name='Suspenso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_schedules', to='routes.busroute', verbose_name='Rota')),
            ],
            options={
                'verbose_name': 'Horário Especial',
                'verbose_name_plural': 'Horários Especiais',
                'ordering': ['date', 'route__number'],
                'unique_together': {('route', 'date', 'direction')},
            },
        ),
    ]
